### ISSUE TITLE
Misspelligs

### ISSUE THREAD

**Issue by LaZsolt** [SpenceKonde/ProductInfo#2]
I read about your products when I found this:

` MOSFET product page` points to a wrong file. When I try it to reach by a mouse click I get a `Page not found` error.

Another misspelled:

`AVR Breakout Baord page`  Baord Board

<br><br>Your writing about MOSFETs very useful for new (and old) designers. +1 Like :)

**Comment by SpenceKonde** [comment]
Thanks, fixed
